### ISSUE TITLE
Cannot read property 'queryResultType' of null

### ISSUE THREAD

**Issue by DLTKScottLezberg** [Quadrotech/ADOScheduledWorkItemQuery#16]
I am trying to run a basic query and getting the following error "Cannot read property 'queryResultType' of null"

This is on ADO 2019 (on-premise)

Any ideas?

**Comment by jlad00** [comment]
I get this as well when trying to use shared queries. Also on ADO 2019 On Prem.

**Comment by bronder** [comment]
I have this same deal with On Prem 2019.

##[error]Cannot read property 'queryResultType' of null

Thanks,
Scott

**Comment by tomzosh** [comment]
I am also getting this error trying to run a simple shared query.

```
##[debug]task result: Failed
##[error]Cannot read property 'queryResultType' of null
##[debug]Processed: ##vso[task.issue type=error;]Cannot read property 'queryResultType' of null
##[debug]Processed: ##vso[task.complete result=Failed;]Cannot read property 'queryResultType' of null
Finishing: Send Query Result as E-Mail
```

How can I resolve this issue?

**Comment by stuartrainsworth** [comment]
Having the same problem.

**Comment by stuikomma** [comment]
Did you find a solution to this issue?

I guess this is where it fails `switch(result.queryResultType)` because `result` is null.
https://github.com/Quadrotech/ADOScheduledWorkItemQuery/blob/master/ado-scheduledworkitemquery-task/ado-scheduledworkitemquery-taskV1/index.ts#L200

This result comes straight out of [queryById](https://github.com/microsoft/azure-devops-node-api/blob/dcf730b1426fb559d6fe2715223d4a7f3b56ef27/api/WorkItemTrackingApi.ts#L2979), so maybe updating that lib might help?

Here's my `azure-pipelines.yml`

```
pool:
  vmImage: windows-latest

steps:
- task: ADOScheduledWorkItemQuery@0
  inputs:
    sendMethod: 'SMTP'
    connectedServiceNameSMTP: 'SMTP'
    project: <project id>
    queryType: 'Shared'
    query: <query id>
    sendIEmpty: true
    subject: <subject>
    emailAddresses: <email>
```

The pipeline log ends with:
```
##[debug]queryType=Shared
##[debug]query=<query id>
##[debug]null=Shared
##[debug]task result: Failed
##[error]Cannot read property 'queryResultType' of null
```
